package View;

import Controller.Method;
import Controller.MethodRandom;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author richy
 */
public class DeletePersonVW extends javax.swing.JFrame {

    /**
     * Creates new form DeletePersonVW
     */
    public DeletePersonVW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDeletePerson = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnDeleteText = new javax.swing.JButton();
        btnDeleteBinary = new javax.swing.JButton();
        btnDeleteRandom = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("DIgite nombre o telefono:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminar en:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        btnDeleteText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageText.png"))); // NOI18N
        btnDeleteText.setText("Texto");
        btnDeleteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTextActionPerformed(evt);
            }
        });

        btnDeleteBinary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/binary.png"))); // NOI18N
        btnDeleteBinary.setText("Binario+Texto");
        btnDeleteBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBinaryActionPerformed(evt);
            }
        });

        btnDeleteRandom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shuffle.png"))); // NOI18N
        btnDeleteRandom.setText("Aleatorio");
        btnDeleteRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRandomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDeleteText)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteBinary)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteRandom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteBinary)
                    .addComponent(btnDeleteRandom))
                .addContainerGap())
        );

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reply.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDeletePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDeletePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBinaryActionPerformed
        String eliminar = txtDeletePerson.getText();
        if (eliminar.isEmpty()) {
            JOptionPane.showMessageDialog(null, "por favor ingrese un dato");            
        } else {
            Method m = new Method();
            m.removeLineFromFile("DbBinary.txt", eliminar);
            txtDeletePerson.setText("");
        }
    }//GEN-LAST:event_btnDeleteBinaryActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnDeleteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTextActionPerformed
        String eliminar = txtDeletePerson.getText();
        if (eliminar.isEmpty()) {
            JOptionPane.showMessageDialog(null, "por favor ingrese un dato");            
        } else {
            Method m = new Method();
            m.removeLineFromFile("DbTexto.txt", eliminar);
            //mensaje al usuario
            JOptionPane.showMessageDialog(null, "Se elimino el registro correctamente");
            txtDeletePerson.setText("");
        }
    }//GEN-LAST:event_btnDeleteTextActionPerformed

    private void btnDeleteRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRandomActionPerformed
     String eliminar = txtDeletePerson.getText();
        if (eliminar.isEmpty()) {
            JOptionPane.showMessageDialog(null, "por favor ingrese un dato");            
        } else {
            Method m = new Method();
            m.removeLineFromFile("AccessRandom.dat", eliminar);
            JOptionPane.showMessageDialog(null, "Se elimino el registro correctamente");
            txtDeletePerson.setText("");
        }
    }//GEN-LAST:event_btnDeleteRandomActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteBinary;
    private javax.swing.JButton btnDeleteRandom;
    private javax.swing.JButton btnDeleteText;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDeletePerson;
    // End of variables declaration//GEN-END:variables
}
