
package View;

import Controller.Method;
import Model.Person;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhon
 */
public class SearchVW extends javax.swing.JFrame {
    
    AddPersonVW f = new AddPersonVW();
    
    public SearchVW() {
        initComponents();
        btnAgregar.setVisible(false);
        lcrear.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtbuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        lresultado = new javax.swing.JLabel();
        lcrear = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnSearchText = new javax.swing.JButton();
        btnSearchBinary = new javax.swing.JButton();
        btnSearchRandom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Buscar por Nombre:");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Datos Encontrados:");

        btnAtras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reply.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        lresultado.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lresultado.setText("--");

        lcrear.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lcrear.setText("Desea crear el registro ?");

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-user.png"))); // NOI18N
        btnAgregar.setText("Crear");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opcion de Busqueda"));

        btnSearchText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearchText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageText.png"))); // NOI18N
        btnSearchText.setText("Texto");
        btnSearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTextActionPerformed(evt);
            }
        });

        btnSearchBinary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/binary.png"))); // NOI18N
        btnSearchBinary.setText("BInario+Texto");
        btnSearchBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBinaryActionPerformed(evt);
            }
        });

        btnSearchRandom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shuffle.png"))); // NOI18N
        btnSearchRandom.setText("Aleatorio");
        btnSearchRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchRandomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnSearchText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchBinary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchRandom)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearchRandom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearchBinary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearchText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lcrear, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addGap(39, 39, 39))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lresultado)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAtras))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lresultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(lcrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTextActionPerformed
        String buscar = txtbuscar.getText();
        if(buscar.isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor digite un dato");
        }else{
        try {
            final BufferedReader reader = new BufferedReader(new FileReader("DbTexto.txt"));
            String line = "";
            while ((line = reader.readLine()) != null) {
                if (line.indexOf(buscar) != -1) {
                   
                    lresultado.setText(line);
                    btnAgregar.setVisible(false);
                    lcrear.setVisible(false);
                    break;
                }else{
                    lresultado.setText("No existe registro el dato: " + buscar);
                    btnAgregar.setVisible(true);
                    lcrear.setVisible(true);
                    f.txtNombre.setText(buscar);
                    
                }
                
            }
            reader.close();
        } catch (FileNotFoundException e) {
           
            e.printStackTrace();
        } catch (IOException e) {
       
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_btnSearchTextActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        AddPersonVW p = new AddPersonVW();
        p.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSearchBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBinaryActionPerformed
        String buscar = txtbuscar.getText();
        if(buscar.isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor digite un dato");
        }else{
        try {
            final BufferedReader reader = new BufferedReader(new FileReader("DbBinary.txt"));
            String line = "";
            while ((line = reader.readLine()) != null) {
                if (line.indexOf(buscar) != -1) {
                   
                    lresultado.setText(line);
                    btnAgregar.setVisible(false);
                    lcrear.setVisible(false);
                    break;
                }else{
                    lresultado.setText("No existe registro el dato: " + buscar);
                    btnAgregar.setVisible(true);
                    lcrear.setVisible(true);
                    f.txtNombre.setText(buscar);
                    
                }
                
            }
            reader.close();
        } catch (FileNotFoundException e) {
           
            e.printStackTrace();
        } catch (IOException e) {
       
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_btnSearchBinaryActionPerformed

    private void btnSearchRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchRandomActionPerformed
        String buscar = txtbuscar.getText();
        if(buscar.isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor digite un dato");
        }else{
        try {
            final BufferedReader reader = new BufferedReader(new FileReader("AccessRandom.dat"));
            String line = "";
            while ((line = reader.readLine()) != null) {
                if (line.indexOf(buscar) != -1) {
                   
                    lresultado.setText(line);
                    btnAgregar.setVisible(false);
                    lcrear.setVisible(false);
                    break;
                }else{
                    lresultado.setText("No existe registro el dato: " + buscar);
                    btnAgregar.setVisible(true);
                    lcrear.setVisible(true);
                    f.txtNombre.setText(buscar);
                    
                }
                
            }
            reader.close();
        } catch (FileNotFoundException e) {
           
            e.printStackTrace();
        } catch (IOException e) {
       
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_btnSearchRandomActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Buscar().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnSearchBinary;
    private javax.swing.JButton btnSearchRandom;
    private javax.swing.JButton btnSearchText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lcrear;
    private javax.swing.JLabel lresultado;
    public static javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
